add_user:
  path: /user
  controller: App\Controller\Api\UserController::create
  methods: POST

get_users:
  path: /user
  controller: App\Controller\Api\UserController::all
  methods: GET

create_group:
  path: /group
  controller: App\Controller\Api\GroupController::create
  methods: POST

get_groups:
  path: /group
  controller: App\Controller\Api\GroupController::all
  methods: GET

delete_group:
  path: /group/{id}
  controller: App\Controller\Api\GroupController::delete
  methods: DELETE
  requirements:
    id: '\d+'

assign_user_to_group:
  path: /group/{groupId}/assign
  controller: App\Controller\Api\GroupController::assignUser
  methods: POST
  requirements:
    groupId: '\d+'

remove_user_from_group:
  path: /group/{groupId}/remove
  controller: App\Controller\Api\GroupController::removeUser
  methods: DELETE
  requirements:
    groupId: '\d+'
