add_user:
  path: /user
  controller: App\Controller\UserController::addUser
  methods: POST

get_users:
  path: /user
  controller: App\Controller\UserController::getUsers
  methods: GET

create_group:
  path: /group
  controller: App\Controller\GroupController::createGroup
  methods: POST

get_groups:
  path: /group
  controller: App\Controller\GroupController::getGroups
  methods: GET