add_user:
  path: /user
  controller: App\Controller\UserController::addUser
  methods: POST

get_users:
  path: /user
  controller: App\Controller\UserController::getUsers
  methods: GET

create_group:
  path: /group
  controller: App\Controller\GroupController::create
  methods: POST

delete_group:
  path: /group
  controller: App\Controller\GroupController::delete
  methods: DELETE

get_groups:
  path: /group
  controller: App\Controller\GroupController::getGroups
  methods: GET

assign_user_to_group:
  path: /group/assign
  controller: App\Controller\GroupController::assignUser
  methods: POST

remove_user_from_group:
  path: /group/remove
  controller: App\Controller\GroupController::removeUser
  methods: POST